### ISSUE TITLE
about:addons wrong website url

### ISSUE THREAD

**Issue by frmariam** [tarakbumba/silbe-for-palemoon#1]
Minor issue.
The url visible in about:addons leads to a 404:
https://github.com/tarakbumba/search-in-locationbar-extended
(instead of https://github.com/tarakbumba/silbe-for-palemoon )

PS: thank you very much for this fork!
This was one of the extensions keeping me on PM 29.1.1 (though I'm still there for X-Notifier Reloaded an Lazarus).
It even seems to have fixed an old odd issue I had with the reload "button" appearing as outside the location bar (now it's as it was supposed to look).

**Comment by tarakbumba** [comment]
Thank you for your report. Should be fixed now.
